version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Open_Landscapes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  django:
    image: django-docker:0.0.1
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DEBUG: 1
      SECRET_KEY: "insecure-secret-key"
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 89.36.211.235
      DATABASE_URL: postgres://postgres:admin@db:5432/Open_Landscapes

volumes:
  postgres_data:
