# Generated by Django 5.2 on 2025-04-30 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='research',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_base_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.basemap'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_country',
            field=models.ForeignKey(blank=True, db_column='id_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.country'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_first_discovery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.firstdiscoverymethod'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_municipality',
            field=models.ForeignKey(blank=True, db_column='id_municipality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.municipality'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_physiography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.physiography'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_positional_accuracy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positionalaccuracy'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_positioning_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positioningmode'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_province',
            field=models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.region'),
        ),
        migrations.AlterField(
            model_name='site',
            name='locality_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
