# Generated by Django 5.2 on 2025-05-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_archaeologicalevidence_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='sigla_provincia',
            field=models.ForeignKey(blank=True, db_column='sigla_provincia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province'),
        ),
        migrations.AlterField(
            model_name='province',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.region'),
        ),
    ]
