# Generated by Django 5.2 on 2025-05-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_municipality_sigla_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='codice_regione',
            field=models.ForeignKey(db_column='codice_regione', default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='id_region',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
