# Generated by Django 5.2 on 2025-05-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_province_codice_regione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='codice_regione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_base_map',
            field=models.ForeignKey(blank=True, db_column='id_base_map', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.basemap'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_first_discovery_method',
            field=models.ForeignKey(blank=True, db_column='id_first_discovery_method', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.firstdiscoverymethod'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_physiography',
            field=models.ForeignKey(blank=True, db_column='id_physiography', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.physiography'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_positional_accuracy',
            field=models.ForeignKey(blank=True, db_column='id_positional_accuracy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positionalaccuracy'),
        ),
        migrations.AlterField(
            model_name='site',
            name='id_positioning_mode',
            field=models.ForeignKey(blank=True, db_column='id_positioning_mode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.positioningmode'),
        ),
        migrations.AlterField(
            model_name='site',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
