# Generated by Django 5.2 on 2025-05-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_site_id_alter_sitetoponymy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='id_region',
        ),
        migrations.AddField(
            model_name='image',
            name='id_site',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='id_province',
            field=models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='chronology_certainty_level',
            field=models.IntegerField(blank=True, db_column='chronology_certainty_level', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id_chronology',
            field=models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chronology'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id_functional_class',
            field=models.ForeignKey(blank=True, db_column='id_functional_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.functionalclass'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id_typology',
            field=models.ForeignKey(blank=True, db_column='id_typology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.typology'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='id_typology_detail',
            field=models.ForeignKey(blank=True, db_column='id_typology_detail', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.typologydetail'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', null=True),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='id_investigation_type',
            field=models.ForeignKey(blank=True, db_column='id_investigation_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.investigationtype'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='id_site',
            field=models.IntegerField(db_column='id_site'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sigla_provincia',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='researchauthor',
            name='id_author',
            field=models.ForeignKey(blank=True, db_column='id_author', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.author'),
        ),
        migrations.AlterField(
            model_name='researchauthor',
            name='id_research',
            field=models.ForeignKey(blank=True, db_column='id_research', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.research'),
        ),
        migrations.AlterField(
            model_name='siteresearch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='siteresearch',
            name='id_research',
            field=models.ForeignKey(db_column='id_research', on_delete=django.db.models.deletion.CASCADE, to='frontend.research'),
        ),
        migrations.AlterField(
            model_name='siteresearch',
            name='id_site',
            field=models.ForeignKey(db_column='id_site', on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
