# Generated by Django 5.2 on 2025-12-12 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_add_audit_logging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='authored_by',
                to=settings.AUTH_USER_MODEL,
                db_column='user_id',
                help_text='User account linked to this author (optional)'
            ),
        ),
    ]
