# Generated by Django 5.0 on 2026-01-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_remove_author_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'site_investigation',
            },
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='access_log_timesta_f9acc6_idx',
            old_name='access_log_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='access_log_user_id_3072cd_idx',
            old_name='access_log_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_timesta_8b04a8_idx',
            old_name='audit_log_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_user_id_79f582_idx',
            old_name='audit_log_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_model_n_1435ea_idx',
            old_name='audit_log_model_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_operati_934dc6_idx',
            old_name='audit_log_operation_timestamp_idx',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='type',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='id_site',
        ),
        migrations.AddField(
            model_name='archaeologicalevidence',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='chronology_certainty_level',
            field=models.IntegerField(blank=True, db_column='chronology_certainty_level', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_archaeological_evidence_typology',
            field=models.ForeignKey(blank=True, db_column='id_archaeological_evidence_typology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.archaeologicalevidencetypology'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_base_map',
            field=models.ForeignKey(blank=True, db_column='id_base_map', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.basemap'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_chronology',
            field=models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.chronology'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_country',
            field=models.ForeignKey(blank=True, db_column='id_country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.country'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_first_discovery_method',
            field=models.ForeignKey(db_column='id_first_discovery_method', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.firstdiscoverymethod'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_investigation',
            field=models.ForeignKey(blank=True, db_column='id_investigation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.investigation'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_municipality',
            field=models.ForeignKey(blank=True, db_column='id_municipality', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.municipality'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_physiography',
            field=models.ForeignKey(blank=True, db_column='id_physiography', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.physiography'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_positional_accuracy',
            field=models.ForeignKey(db_column='id_positional_accuracy', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.positionalaccuracy'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_positioning_mode',
            field=models.ForeignKey(db_column='id_positioning_mode', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.positioningmode'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_province',
            field=models.ForeignKey(blank=True, db_column='id_province', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.province'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.region'),
        ),
        migrations.AlterField(
            model_name='archaeologicalevidence',
            name='locality_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archevbiblio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archevbiblio',
            name='id_archaeological_evidence',
            field=models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.archaeologicalevidence'),
        ),
        migrations.AlterField(
            model_name='archevbiblio',
            name='id_bibliography',
            field=models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.bibliography'),
        ),
        migrations.AlterField(
            model_name='archevrelateddoc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archevrelateddoc',
            name='id_archaeological_evidence',
            field=models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence'),
        ),
        migrations.AlterField(
            model_name='archevresearch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archevresearch',
            name='id_archaeological_evidence',
            field=models.ForeignKey(db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.archaeologicalevidence'),
        ),
        migrations.AlterField(
            model_name='archevresearch',
            name='id_research',
            field=models.ForeignKey(db_column='id_research', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.research'),
        ),
        migrations.AlterField(
            model_name='archevsources',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archevsources',
            name='id_archaeological_evidence',
            field=models.ForeignKey(blank=True, db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.archaeologicalevidence'),
        ),
        migrations.AlterField(
            model_name='archevsources',
            name='id_sources',
            field=models.ForeignKey(db_column='id_sources', on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.sources'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='interpretationbibliography',
            name='id_bibliography',
            field=models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.bibliography'),
        ),
        migrations.AlterField(
            model_name='interpretationbibliography',
            name='id_interpretation',
            field=models.ForeignKey(blank=True, db_column='id_interpretation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.interpretation'),
        ),
        migrations.AlterField(
            model_name='province',
            name='superficie_kmq',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AlterField(
            model_name='sitearchevidence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitearchevidence',
            name='id_archaeological_evidence',
            field=models.ForeignKey(db_column='id_archaeological_evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.archaeologicalevidence'),
        ),
        migrations.AlterField(
            model_name='sitearchevidence',
            name='id_site',
            field=models.ForeignKey(db_column='id_site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='sitebibliography',
            name='id_bibliography',
            field=models.ForeignKey(blank=True, db_column='id_bibliography', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.bibliography'),
        ),
        migrations.AlterField(
            model_name='sitebibliography',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='siterelateddocumentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='siterelateddocumentation',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='siteresearch',
            name='id_research',
            field=models.ForeignKey(db_column='id_research', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.research'),
        ),
        migrations.AlterField(
            model_name='siteresearch',
            name='id_site',
            field=models.ForeignKey(db_column='id_site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='sitesources',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='sitesources',
            name='id_sources',
            field=models.ForeignKey(db_column='id_sources', on_delete=django.db.models.deletion.CASCADE, to='frontend.sources'),
        ),
        migrations.AlterField(
            model_name='sitetoponymy',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='id_chronology',
            field=models.ForeignKey(blank=True, db_column='id_chronology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chronology'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='id_sources_typology',
            field=models.ForeignKey(blank=True, db_column='id_sources_typology', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.sourcestype'),
        ),
        migrations.AlterField(
            model_name='typologydetail',
            name='id_functional_class',
            field=models.ForeignKey(blank=True, db_column='id_functional_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.functionalclass'),
        ),
        migrations.AddConstraint(
            model_name='archevresearch',
            constraint=models.UniqueConstraint(fields=('id_archaeological_evidence', 'id_research'), name='unique_arch_ev_research_pair'),
        ),
        migrations.AddField(
            model_name='siteinvestigation',
            name='id_investigation',
            field=models.ForeignKey(blank=True, db_column='id_investigation', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.investigation'),
        ),
        migrations.AddField(
            model_name='siteinvestigation',
            name='id_site',
            field=models.ForeignKey(blank=True, db_column='id_site', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.site'),
        ),
    ]
